version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./resumeboost.db:/app/resumeboost.db
    environment:
      - DATABASE_URL=sqlite:///./resumeboost.db
